# -*- coding: utf-8 -*-
"""Evenoddchecker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uh7-TneVXi4kXRoAF0ZGTvAJQSyQ4sLb
"""

# Check if a number is Even or Odd

def check_even_odd():
    try:
        num = int(input("Enter an integer: "))
        if num % 2 == 0:
            print(f"{num} is Even.")
        else:
            print(f"{num} is Odd.")
    except ValueError:
        print("Invalid input. Please enter an integer.")

# Run the function
check_even_odd()