# -*- coding: utf-8 -*-
"""mouse_keyboard_ops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SevITTBBf7XShGv-R_D_DbV8q8QfdvOj
"""

import pyautogui
import time

print("Starting in 3 seconds...")
time.sleep(3)

pyautogui.moveTo(100, 100, duration=1)
pyautogui.click()
pyautogui.typewrite("Hello, world!", interval=0.25)