# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DL7jFaGtHBTVFQxqgQie0nNb83QzuCpK
"""

# Step 1: Ask for user input
name = input("What is your name? ")
age = input("How old are you? ")
favourite_colour = input("What is your favorite colour? ")

# Step 2: Create a personalized message
message = f"Hello {name}! Did you know that {favourite_colour} looks amazing on someone who is {age} years young?"

# Step 3: Print the message
print("\nHere's your personalized message:\n")
print(message)