# -*- coding: utf-8 -*-
"""Printing_latestmail.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12NK5PPpnl1rtO7v_xDe-NwSh6nWLAbvg
"""

# Step 2: Import async libraries
from playwright.async_api import async_playwright
import asyncio

# Step 3: Define Gmail credentials
email = "your_email@gmail.com"
password = "your_app_password"  # Use App Password if 2FA is enabled


# Step 4: Define the async function
async def scrape_latest_email():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context()

        page = await context.new_page()

        # Go to Gmail login page
        await page.goto("https://accounts.google.com/signin/v2/identifier?service=mail")
        print("Gmail login page loaded.")

        # Fill in email
        await page.fill('input[type="email"]', email)
        await page.click('#identifierNext')
        await asyncio.sleep(2)

        # Fill in password
        await page.fill('input[type="password"]', password)
        await page.click('#passwordNext')
        await asyncio.sleep(5)  # Wait for login

        # Go to inbox
        await page.goto(" https://mail.google.com/mail/u/0/#inbox")
        await asyncio.sleep(5)

        # Click on latest email
        await page.click('tr.zA td span[email]')
        await asyncio.sleep(3)

        # Get subject and body text
        subject = await page.text_content('h2.hP')
        body = await page.text_content('div.adn.ads div div div[dir="ltr"]')

        print("\n=== Latest Email ===")
        print("Subject:", subject)
        print("Body:\n", body[:500] + "...")  # Print first 500 chars of body

        await context.close()


# Step 5: Run the async function
await scrape_latest_email()