# -*- coding: utf-8 -*-
"""Whatsapp_message_sending.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DL7jFaGtHBTVFQxqgQie0nNb83QzuCpK
"""

import pyautogui
import time
import pyttsx3
import webbrowser

# Initialize text-to-speech engine
engine = pyttsx3.init()

def speak(text):
    engine.say(text)
    engine.runAndWait()

def send_whatsapp_message(contact_name, message):
    # Open WhatsApp Web
    webbrowser.open("https://web.whatsapp.com ")
    speak("Opening WhatsApp Web. Please wait.")
    time.sleep(15)  # Wait for WhatsApp Web to load

    # Click on search bar
    pyautogui.hotkey('ctrl', 'alt', 'slash')  # Focus on search bar (alternative)
    time.sleep(2)

    # Type the contact's name
    speak(f"Searching for {contact_name}")
    pyautogui.write(contact_name)
    time.sleep(2)

    # Select the contact
    pyautogui.press('enter')
    time.sleep(2)

    # Type the message
    speak("Typing message")
    pyautogui.write(message)
    time.sleep(1)

    # Send the message
    pyautogui.press('enter')
    speak("Message sent successfully!")

# --- Main Execution ---
if __name__ == "__main__":
    contact = "John Doe"  # Replace with actual contact name
    msg = "Hello from Python automation!"

    print("Make sure WhatsApp Web is open and you're logged in.")
    input("Press Enter to start...")

    send_whatsapp_message(contact, msg)